version: "3"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=book_store_dev
      - POSTGRES_USER=vinhle
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    entrypoint: ["sh", "./wait-for-postgres.sh"]
    command: "python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://vinhle:password@db/book_store_dev"

volumes:
  dbdata: